### ISSUE TITLE
Error: "discordsdk.exception.not_running: result 27"

### ISSUE THREAD

**Issue by ranidspace** [LennyPhoenix/py-discord-sdk#16]
I am on Debian 12, running Python 3.11.2, with version 0.2.5 of discordsdk

I ran the first example program, the "Create a Discord instance" and replaced the APPLICATION_ID with the one I have.
Discord is open, and installed unsandboxed, and works with other game activities and applications which use Rich Presence.

When running the file, it output the following:
```
Traceback (most recent call last):
  File "/home/[user]/applications/testapp/testapp.py", line 10, in <module>
    app.run_callbacks()
  File "/home/[user]/.local/lib/python3.11/site-packages/discordsdk/discord.py", line 94, in run_callbacks
    raise get_exception(result)
discordsdk.exception.not_running: result 27
```

**Comment by LennyPhoenix** [comment]
Hi there!

It's been a while since I've worked on this project, but I do remember randomly encountering this problem from time to time.

I believe restarting my computer would help usually, but let me know if you've tried that already and it didn't help!

**Comment by LennyPhoenix** [comment]
It might also be worth trying a newer version of the SDK to see if it fixes the problem.

**Comment by ranidspace** [comment]
oh wow, i didnt realize the last commit was 3 years ago haha thats crazy, i'll restart my computer and try out a newer sdk and hope it works

**Comment by LennyPhoenix** [comment]
Shocked it even still installs tbh haha, hope it works!

**Comment by LennyPhoenix** [comment]
I'd also bear in mind that since early 2023, the SDK has been pretty much completely axed by Discord. I can't really guarantee any support for the SDK at all now, let alone for this module...
